//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalNetworkHardware.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocalNetworkHardwareManagement_DBEntities : DbContext
    {
        public LocalNetworkHardwareManagement_DBEntities()
            : base("name=LocalNetworkHardwareManagement_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CdROMs> CdROMs { get; set; }
        public virtual DbSet<CPUs> CPUs { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<GPUs> GPUs { get; set; }
        public virtual DbSet<NetworkAdapters> NetworkAdapters { get; set; }
        public virtual DbSet<OpratingSystems> OpratingSystems { get; set; }
        public virtual DbSet<Printers> Printers { get; set; }
        public virtual DbSet<RAMs> RAMs { get; set; }
        public virtual DbSet<SoundCards> SoundCards { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Systems> Systems { get; set; }
        public virtual DbSet<Activities> Activities { get; set; }
    }
}
